###BACKEND####
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: api
  replicas: 2
  template:
    metadata:
      labels:
        app: api

    spec:
      hostname: api
      subdomain: backend
      containers:
        - name: api
          image: "noloknolo/jira_server:2.1"
          #image: ${SERVER_IMAGE}

          resources:
            requests:
              cpu: 250m
              memory: "400Mi"
            limits: 
              cpu: 500m
              memory: "600Mi"
          ports:
            - name: tcp
              containerPort: 3000
          # Validacion desactivada W.I.P
          # livenessProbe:
          #   httpGet:
          #     path: "/"
          #     port: 3000
          #   initialDelaySeconds: 3
          #   periodSeconds: 3

---


###FRONTEND###

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: client

  replicas: 2
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: "noloknolo/jira_client:2.1"
          #image: ${CLIENT_IMAGE}
          resources:
            requests:
              cpu: 250m
              memory: "400Mi"
            limits: 
              cpu: 500m
              memory: "600Mi"
          #livenessProbe:
           # httpGet:
            #  path: "/"
            #  port: 8080
            #initialDelaySeconds: 3
            #periodSeconds: 3

---

##SERVICES###

apiVersion: v1
kind: Service
metadata:
  name: front-service
spec:

  selector:
    app: front
  ports:
  - protocol: "TCP"
    name: front
    port: 8080
    targetPort: 8080
  type: LoadBalancer

---

kind: Service
apiVersion: v1
metadata:
  name:  api
spec:
  selector:
    app:  api
  type:  ClusterIP
  ports:
  - name:  back
    port:  3000
    targetPort:  3000

# api.default.svc.cluster.local